# Generated by Django 5.0.1 on 2025-06-26 07:39

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('size', models.CharField(choices=[('small', '1-50 employees'), ('medium', '51-250 employees'), ('large', '251-1000 employees'), ('enterprise', '1000+ employees')], max_length=20)),
                ('description', models.TextField(max_length=10000)),
                ('logo', models.CharField(blank=True, max_length=8000000, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=128, unique=True)),
                ('username', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('profile_picture', models.CharField(blank=True, max_length=8000000, null=True)),
                ('user_type', models.CharField(choices=[('recruiter', 'Recruiter'), ('jobseeker', 'Job Seeker')], max_length=10)),
                ('bio', models.TextField(max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=250)),
                ('salary', models.BigIntegerField()),
                ('employment_type', models.CharField(choices=[('Full Time', 'Full-Time'), ('Part Time', 'Part-Time')], max_length=20)),
                ('posted_date', models.DateField()),
                ('application_deadline', models.DateField()),
                ('requirements', models.TextField(max_length=65535)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='myapp.company')),
            ],
        ),
        migrations.CreateModel(
            name='JobSeekerProfile',
            fields=[
                ('jobseeker_id', models.AutoField(primary_key=True, serialize=False)),
                ('experience_years', models.IntegerField(null=True)),
                ('achievements', models.CharField(blank=True, max_length=1000, null=True)),
                ('job_type_preference', models.CharField(choices=[('Full Time', 'Full-Time'), ('Part Time', 'Part-Time')], max_length=20)),
                ('preferred_job_roles', models.CharField(max_length=500, null=True)),
                ('consent_box', models.BooleanField(default=False)),
                ('relocate_confirmation', models.BooleanField(default=False)),
                ('job_search_status', models.CharField(choices=[('available', 'Available to Start'), ('looking', 'Just Looking'), ('not_looking', 'Not Looking')], default='looking', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_seeker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('application_date', models.DateField()),
                ('status', models.CharField(choices=[('p', 'pending'), ('a', 'accepted'), ('r', 'rejected')], default='p', max_length=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.jobs')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.jobseekerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('postal_code', models.CharField(max_length=10)),
            ],
            options={
                'indexes': [models.Index(fields=['country', 'state', 'city'], name='myapp_locat_country_31a6d9_idx')],
            },
        ),
        migrations.AddField(
            model_name='jobs',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.location'),
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.location'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.location'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=65535)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('new_job', 'new job'), ('application_status', 'application status')], max_length=50)),
                ('message', models.TextField(max_length=1500)),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('read_status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecruiterProfile',
            fields=[
                ('recruiter_id', models.AutoField(primary_key=True, serialize=False)),
                ('fssai_license_no', models.CharField(max_length=250)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiters', to='myapp.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='jobs',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.recruiterprofile'),
        ),
        migrations.AddConstraint(
            model_name='applications',
            constraint=models.UniqueConstraint(fields=('job_id', 'applicant_id'), name='unique_job_application'),
        ),
        migrations.AddIndex(
            model_name='jobs',
            index=models.Index(fields=['title', 'employment_type'], name='myapp_jobs_title_20bd2f_idx'),
        ),
    ]
